#' Generate a random color palette for fill aesthetics in ggplot2.
#'
#' This function creates a custom scale for filling aesthetics in ggplot2
#' with a random color palette generated by the rand_color function.
#'
#' @param hue The hue value for generating random colors (optional).
#' @param luminosity The luminosity of the colors (default is "light").
#' @param seed An optional seed for reproducible random color generation.
#' @param transparency The level of transparency for the colors (default is 0).
#' @param friendly Should friendly colors be generated? (default is FALSE).
#' @param ... Additional arguments to pass to rand_color function.
#' @param aesthetics The aesthetic to scale (default is "fill").
#'
#' @return A ggplot2 scale for fill aesthetics with a random color palette.
#'
#' @importFrom circlize rand_color
#' @importFrom ggplot2 discrete_scale
#'
#' @export
scale_fill_random <- function(hue = NULL,
                              luminosity = "light",seed = NULL,
                              transparency = 0, friendly = FALSE,
                              ..., aesthetics = "fill") {

  discrete_scale(
    aesthetics = aesthetics,
    scale_name = "random",
    palette = function(n){
      if(!is.null(seed)) set.seed(seed)
      rand_color(n = n, hue = hue,
                 luminosity = luminosity,
                 transparency = transparency, friendly = friendly)
    }
  )
}




#' Generate a random color palette for color aesthetics in ggplot2.
#'
#' This function creates a custom scale for color aesthetics in ggplot2
#' with a random color palette generated by the rand_color function.
#'
#' @param hue The hue value for generating random colors (optional).
#' @param luminosity The luminosity of the colors (default is "light").
#' @param seed An optional seed for reproducible random color generation.
#' @param transparency The level of transparency for the colors (default is 0).
#' @param friendly Should friendly colors be generated? (default is FALSE).
#' @param ... Additional arguments to pass to rand_color function.
#' @param aesthetics The aesthetic to scale (default is "color").
#'
#' @return A ggplot2 scale for color aesthetics with a random color palette.
#'
#' @importFrom ggplot2 discrete_scale
#'
#' @export
scale_color_random <- function(hue = NULL,
                               luminosity = "light", seed = NULL,
                               transparency = 0, friendly = FALSE,
                               ..., aesthetics = "color") {
  discrete_scale(
    aesthetics = aesthetics,
    scale_name = "random",
    palette = function(n){
      if(!is.null(seed)) set.seed(seed)
      rand_color(n = n, hue = hue,
                 luminosity = luminosity,
                 transparency = transparency, friendly = friendly)
    }
  )
}
